check for uncommitted dist changes

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -52,3 +52,11 @@ jobs:
 
       - name: Build
         run: pnpm build
+
+      - name: Check for uncommitted dist changes
+        run: |
+          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
+              echo "::error::Detected uncommitted changes in dist/ directory after build. Please run 'pnpm build' locally and commit the changes."
+              git --no-pager diff dist/
+              exit 1
+          fi
